format_version: 10
pipelines:
  ml_pipeline:
    group: kubernetes
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      gocd:
        git: https://github.com/CheahChernEu/gocd.git
        username: tennischeah@gmail.com
        shallow_clone: false
        auto_update: true
        branch: main
        encrypted_password: AES:l6u/A+LrXVRI5C+q27Dn2Q==:EM7ycjGZHfL40aLBvZ57zg==
    stages:
    - Deploy:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          deploy_k8s:
            timeout: 0
            elastic_profile_id: gocd_elastic_agent
            tasks:
            - exec:
                command: ./build
                run_if: passed



